apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: kruise-state-metrics
    app.kubernetes.io/version: 0.0.1
  name: kruise-state-metrics
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kruise-state-metrics
subjects:
- kind: ServiceAccount
  name: kruise-state-metrics
  namespace: kruise-system
